### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Jukebox#7]
@zenangst @RamonGilabert So apparently we need another name.
Soundbox, Musicbox, Orchestra, Orchestrion. 
Any other suggestions? :smiley:

**Comment by RamonGilabert** [comment]
Sounds?

**Comment by RamonGilabert** [comment]
Floppy Jukebox?

**Comment by RamonGilabert** [comment]
<img width="269" alt="screen shot 2016-01-06 at 9 26 20 am" src="https://cloud.githubusercontent.com/assets/6138120/12138226/8e313e5a-b457-11e5-81b1-76d4db58f824.png">

**Comment by zenangst** [comment]
`Accordion`, `Harmonica`, `UISounds`, `Cowbell`

**Comment by RamonGilabert** [comment]
UISounds? :smile:

**Comment by zenangst** [comment]
@RamonGilabert It's descriptive ;) But adding `UI` to something is DANGER!

**Comment by zenangst** [comment]
`Sounds Effects`

**Comment by RamonGilabert** [comment]
Mixer, DJs.

**Comment by RamonGilabert** [comment]
Choir?

**Comment by zenangst** [comment]
`Soundtrack`, `Score`, `Noise`, `Echo`, `Melody`, `Tune`, `Harmony`, `Hymn`

**Comment by zenangst** [comment]
I think we have a lot of good suggestions here, do we have any runner-ups?

**Comment by RamonGilabert** [comment]
To me: Orchestra, Choir, Melody and Harmonica.
Accessit: Floppy Jukebox.

**Comment by vadymmarkov** [comment]
Considering that the main feature is to play UI sounds automatically, I like `Sounds`, `Soundbox`, `Musicbox`,  `Orchestra `. `Cowbell` is also interesting :smile:

**Comment by RamonGilabert** [comment]
I like sounds too! So the ones that go into the finals for now are Sounds and Orchestra! :open_mouth:

**Comment by zenangst** [comment]
https://www.youtube.com/watch?v=GCd0OjjCz88

**Comment by zenangst** [comment]
I think we can go for `Sounds`, I like that one. It is straight to the point and you don't really have to wonder what it does because of the app context.

**Comment by vadymmarkov** [comment]
Yeah, probably `Sounds` is the best one. `Orchestra` could have a nice cover though :smile: 
![the-london-symphony-orchestra](https://cloud.githubusercontent.com/assets/10529867/12139396/813b3e9a-b460-11e5-806f-63fc6a3ea41f.jpeg)

Or there is one more name - Symphony, but it reminds me PHP :smile:

**Comment by RamonGilabert** [comment]
Love that picture!

**Comment by toothfairy** [comment]
@vadymmarkov in php it's called symfony

**Comment by vadymmarkov** [comment]
@toothfairy :smile: I know, but still.

**Comment by zenangst** [comment]
Let's go with `Sounds` and close this sucker :sunglasses:

**Comment by vadymmarkov** [comment]
All right, and the last proposal - `SoundKit` :smile:

**Comment by RamonGilabert** [comment]
Melodies? :open_mouth:

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert So guys, what is the final name? `Sounds`, no kits or other stuff?

**Comment by zenangst** [comment]
I like the sound of `Sounds` :grin:

**Comment by vadymmarkov** [comment]
Ok, then long live `Sounds`!

**Comment by vadymmarkov** [comment]
@RamonGilabert @zenangst I feel like `Sounds` is too simple and obvious. `Orchestra` is also a nifty name so I propose to go with it. What do you guys think?

**Comment by zenangst** [comment]
`Orchestra` is more playful and could make for a kick-ass cover image :sunglasses: 
I'm fine with this change.

**Comment by RamonGilabert** [comment]
Orchestra, Choir or Symphony. :smile:

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert Ok, then Orchestra is a winner with 3 votes. Closing this one again.

**Comment by zenangst** [comment]
:princess:
